title: Omics Data Driven PrecisionHealth
description: Description of the Course
repository: AI4PrecisionOmics/Omics_DataDriven_PrecisionHealth
theme: jekyll-theme-cayman
github:
  is_project_page: false
