title: Here is the name of the course
description: Description of the Course
repository: AI4PrecisionOmics/Omics_DataDriven_precisionHealth
theme: jekyll-theme-cayman
github:
  is_project_page: false
